### ISSUE TITLE
Support dot notation for reducerKey

### ISSUE THREAD

**Issue by jancama2** [AckeeCZ/petrus#47]
With the current implementation, we are not able to have reducer nested in other object, lets say:
```
import { reducer as petrus } from '@ackee/petrus';

export { auth: { petrus, login, ... } };
```
This is not possible with the current implementation because for example selectors are implemented like:
```
state[reducerKey]
```
rather than
```
get(reducerKey, state)
```

**Comment by cermakjiri** [comment]
The PR would be very much welcomed :)
